import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class ListService {
  pais:any[]=[
    "Bangladesh",
      "Belgium",
      "Burkina Faso",
      "Bulgaria",
      "Bosnia and Herzegovina",
      "Barbados",
      "Wallis and Futuna",
      "Saint Barthelemy",
      "Bermuda",
      "Brunei",
      "Bolivia",
      "Bahrain",
      "Burundi",
      "Benin",
      "Bhutan",
      "Jamaica",
      "Bouvet Island",
      "Botswana",
      "Samoa",
      "Bonaire, Saint Eustatius and Saba ",
      "Brazil",
      "Bahamas",
      "Jersey",
      "Belarus",
      "Belize",
      "Russia",
      "Rwanda",
      "Serbia",
      "East Timor",
      "Reunion",
      "Turkmenistan",
      "Tajikistan",
      "Romania",
      "Tokelau",
      "Guinea-Bissau",
      "Guam",
      "Guatemala",
      "South Georgia and the South Sandwich Islands",
      "Greece",
      "Equatorial Guinea",
      "Guadeloupe",
      "Japan",
      "Guyana",
      "Guernsey",
      "French Guiana",
      "Georgia",
      "Grenada",
      "United Kingdom",
      "Gabon",
      "El Salvador",
      "Guinea",
      "Gambia",
      "Greenland",
      "Gibraltar",
      "Ghana",
      "Oman",
      "Tunisia",
      "Jordan",
      "Croatia",
      "Haiti",
      "Hungary",
      "Hong Kong",
      "Honduras",
      "Heard Island and McDonald Islands",
      "Venezuela",
      "Puerto Rico",
      "Palestinian Territory",
      "Palau",
      "Portugal",
      "Svalbard and Jan Mayen",
      "Paraguay",
      "Iraq",
      "Panama",
      "French Polynesia",
      "Papua New Guinea",
      "Peru",
      "Pakistan",
      "Philippines",
      "Pitcairn",
      "Poland",
      "Saint Pierre and Miquelon",
      "Zambia",
      "Western Sahara",
      "Estonia",
      "Egypt",
      "South Africa",
      "Ecuador",
      "Italy",
      "Vietnam",
      "Solomon Islands",
      "Ethiopia",
      "Somalia",
      "Zimbabwe",
      "Saudi Arabia",
      "Spain",
      "Eritrea",
      "Montenegro",
      "Moldova",
      "Madagascar",
      "Saint Martin",
      "Morocco",
      "Monaco",
      "Uzbekistan",
      "Myanmar",
      "Mali",
      "Macao",
      "Mongolia",
      "Marshall Islands",
      "Macedonia",
      "Mauritius",
      "Malta",
      "Malawi",
      "Maldives",
      "Martinique",
      "Northern Mariana Islands",
      "Montserrat",
      "Mauritania",
      "Isle of Man",
      "Uganda",
      "Tanzania",
      "Malaysia",
      "Mexico",
      "Israel",
      "France",
      "British Indian Ocean Territory",
      "Saint Helena",
      "Finland",
      "Fiji",
      "Falkland Islands",
      "Micronesia",
      "Faroe Islands",
      "Nicaragua",
      "Netherlands",
      "Norway",
      "Namibia",
      "Vanuatu",
      "New Caledonia",
      "Niger",
      "Norfolk Island",
      "Nigeria",
      "New Zealand",
      "Nepal",
      "Nauru",
      "Niue",
      "Cook Islands",
      "Kosovo",
      "Ivory Coast",
      "Switzerland",
      "Colombia",
      "China",
      "Cameroon",
      "Chile",
      "Cocos Islands",
      "Canada",
      "Republic of the Congo",
      "Central African Republic",
      "Democratic Republic of the Congo",
      "Czech Republic",
      "Cyprus",
      "Christmas Island",
      "Costa Rica",
      "Curacao",
      "Cape Verde",
      "Cuba",
      "Swaziland",
      "Syria",
      "Sint Maarten",
      "Kyrgyzstan",
      "Kenya",
      "South Sudan",
      "Suriname",
      "Kiribati",
      "Cambodia",
      "Saint Kitts and Nevis",
      "Comoros",
      "Sao Tome and Principe",
      "Slovakia",
      "South Korea",
      "Slovenia",
      "North Korea",
      "Kuwait",
      "Senegal",
      "San Marino",
      "Sierra Leone",
      "Seychelles",
      "Kazakhstan",
      "Cayman Islands",
      "Singapore",
      "Sweden",
      "Sudan",
      "Dominican Republic",
      "Dominica",
      "Djibouti",
      "Denmark",
      "British Virgin Islands",
      "Germany",
      "Yemen",
      "Algeria",
      "United States",
      "Uruguay",
      "Mayotte",
      "United States Minor Outlying Islands",
      "Lebanon",
      "Saint Lucia",
      "Laos",
      "Tuvalu",
      "Taiwan",
      "Trinidad and Tobago",
      "Turkey",
      "Sri Lanka",
      "Liechtenstein",
      "Latvia",
      "Tonga",
      "Lithuania",
      "Luxembourg",
      "Liberia",
      "Lesotho",
      "Thailand",
      "French Southern Territories",
      "Togo",
      "Chad",
      "Turks and Caicos Islands",
      "Libya",
      "Vatican",
      "Saint Vincent and the Grenadines",
      "United Arab Emirates",
      "Andorra",
      "Antigua and Barbuda",
      "Afghanistan",
      "Anguilla",
      "U.S. Virgin Islands",
      "Iceland",
      "Iran",
      "Armenia",
      "Albania",
      "Angola",
      "Antarctica",
      "American Samoa",
      "Argentina",
      "Australia",
      "Austria",
      "Aruba",
      "India",
      "Aland Islands",
      "Azerbaijan",
      "Ireland",
      "Indonesia",
      "Ukraine",
      "Qatar",
      "Mozambique"
  ]

  rubros:any[]=[
    {codigo:'A0', name:	'AGRIC-PECUA-Y-AGROIN'},
    {codigo:'B0', name:	'ARTESANIA, MYPES'},
    {codigo:'C0', name:	'COMERCIO E IMPORTAC'},
    {codigo:'C001', name:	'TAT'},
    {codigo:'C002', name:	'AASS'},
    {codigo:'C003', name:	'Farmacias'},
    {codigo:'C004', name:	'Tradicional'},
    {codigo:'C005', name:	'Otro'},
    {codigo:'C006', name:	'Instituciones'},
    {codigo:'C007', name:	'Canales Alternativos'},
    {codigo:'D0', name:	'CONST-URBAN Y EQUIP'},
    {codigo:'E0', name:	'EDUC-CULTU. Y CIENC'},
    {codigo:'F0', name:	'EXPORT. Y COM. EXT.'},
    {codigo:'G0', name:	'FINANZ., VAL. Y SEG.'},
    {codigo:'H0', name:	'HIDROC-MINE. Y ENERG'},
    {codigo:'I0', name:	'INDUSTRIA Y MANUFAC.'},
    {codigo:'J0', name:	'INST-ENTID. Y ORGAN'},
    {codigo:'K0', name:	'PUBLIC-COMUNIC-IMPR'},
  ];

  //lista de cargos
  positions:any[]=[
    {code:'1', name:'Gerente de Logística'},
    {code:'2', name:'Ejecutivo de Logística'},
    {code:'99', name:'Otro'},
  ];

  constructor(private http:HttpClient) { }
  headers:HttpHeaders= new HttpHeaders({
    'Content-type': 'application/json'
  })

  //devuelve el listado de paises
  getPaisList(){
    return this.pais;
  }

  //devuelve el listado de rubros
  getRubroList(){
    return this.rubros;
  }

  //devuelve el listado de cargos
  getPositionsList(){
    return this.positions
  }
}
